apiVersion: v1
kind: Service
metadata:
  name: api-oauth-server-svc
  namespace: api-service
spec:
  ports:
    - name: api-oauth-server-svc
      port: 80
      targetPort: 80
  selector:
    app: api-oauth-auth-server
  type: ClusterIP