spring:
  config:
    activate:
      on-profile: database-setup
  datasource:
    driver-class-name: ${YOUR_DATABASE_DRIVER}
    url: ${YOUR_DATABASE_URL}
    username: ${YOUR_DATABASE_USER_NAME}
    password: ${YOUR_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
---
spring:
  config:
    activate:
      on-profile: hikari-config
  datasource:
    hikari:
      transaction-isolation: ${SQL_PROD_ISOLATION_LEVEL}
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: ${SQL_PROD_CONNECTION_TIMEOUT}
      validation-timeout: ${SQL_PROD_VALIDATION_TIMEOUT}
      connection-test-query: ${SQL_PROD_TEST_QUERY}
      idle-timeout: 60000
      max-lifetime: 1800000
      pool-name: hikari_pool
