name: TestAll

on:
  pull_request:
    branches:
      - "develop"

permissions:
  contents: read

jobs:
  Integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Launch Test code
        run: ./gradlew clean test